apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-deployment
  labels:
    app: affinity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: affinity-pod
  template:
    metadata:
      name: affinity-pod
      labels:
        app: affinity-pod
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: security
                operator: In
                values:
                - S1
            topologyKey: kubernetes.io/hostname
      containers:
      - name: affinity-pod
        image: docker.io/papatzis1978/test
        ports:
        - containerPort: 8080
