apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology-deployment
  labels:
    app: topology
spec:
  replicas: 5
  selector:
    #matchLabels must match template labels  
    matchLabels:
      app: topology-pod
  template:
    metadata:
      name: topology-pod
      labels:
        app: topology-pod
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: node
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            foo: bar
      - maxSkew: 1
        topologyKey: zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            foo: bar
      containers:
      - image: "docker.io/ocpqe/hello-pod"
        name: hello-pod  
